services:
  frontend:
    build:
      context: ./frontend/invoice-system
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - api-gateway

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - company-service
      - invoice-service

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile.auth
    ports:
      - "3003:3003"

  company-service:
    build:
      context: .
      dockerfile: Dockerfile.company
    ports:
      - "3001:3001"

  invoice-service:
    build:
      context: .
      dockerfile: Dockerfile.invoice
    ports:
      - "3004:3004"

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    depends_on:
      - frontend
      - api-gateway
    command: start --all --config /etc/ngrok.yml
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}